{"name": "realizar busca", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".success\"}\n  (Session info: chrome=88.0.4324.182)\n\n", "trace": "  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\busca_steps.py\", line 63, in step_impl\n    assert(results_page.assercao_mensagem(), 'Seu cadastro foi realizado. Aguarde a revisão e aprovação da sua conta.')\n  File \"C:\\Users\\Jean\\PycharmProjects\\DesafioGlobo01\\pages\\results_page.py\", line 7, in assercao_mensagem\n    return self.driver.find_element_by_css_selector('.success').text\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 598, in find_element_by_css_selector\n    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Dado que acesso o site da Globo", "status": "passed", "start": 1614105769435, "stop": 1614105774084}, {"name": "E clico no botão Novo Cadastro", "status": "passed", "start": 1614105774085, "stop": 1614105775056}, {"name": "Quando Preencho o Formulario", "status": "passed", "start": 1614105775056, "stop": 1614105796464}, {"name": "E Clico no botao solicitar cadastro", "status": "passed", "start": 1614105796464, "stop": 1614105801961}, {"name": "Então Exibe uma nova pagina com uma mensagem de cadastro realizado com sucesso", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".success\"}\n  (Session info: chrome=88.0.4324.182)\n\n", "trace": "  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\busca_steps.py\", line 63, in step_impl\n    assert(results_page.assercao_mensagem(), 'Seu cadastro foi realizado. Aguarde a revisão e aprovação da sua conta.')\n  File \"C:\\Users\\Jean\\PycharmProjects\\DesafioGlobo01\\pages\\results_page.py\", line 7, in assercao_mensagem\n    return self.driver.find_element_by_css_selector('.success').text\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 598, in find_element_by_css_selector\n    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\jean\\pycharmprojects\\desafioglobo01\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1614105801961, "stop": 1614105801980}], "start": 1614105769434, "stop": 1614105801981, "uuid": "b369304d-7f60-4d8b-bd86-4cb021477f19", "historyId": "69e10da83e4a23b71fb97bd91d06724f", "fullName": "fluxo de busca: realizar busca", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "cadastro"}, {"name": "feature", "value": "fluxo de busca"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}